SELECT *
FROM EMPLOYEES
WHERE salary < AVG(salary);

SELECT *
FROM EMPLOYEES
WHERE SALARY < (SELECT AVG(SALARY) FROM EMPLOYEES);

SELECT EMP_ID, SALARY, (SELECT MAX(SALARY) FROM EMPLOYEES) AS MAX_SALARY
FROM EMPLOYEES;

SELECT F_NAME, L_NAME
FROM EMPLOYEES
WHERE B_DATE = (SELECT MIN(B_DATE) FROM EMPLOYEES);

SELECT AVG(SALARY)
FROM (SELECT SALARY
      FROM EMPLOYEES
      ORDER BY SALARY DESC
      LIMIT 5) AS SALARY_TABLE;

--

SELECT AVG(SALARY)
FROM (SELECT SALARY
      FROM EMPLOYEES
      ORDER BY SALARY ASC
      LIMIT 5) AS SALARY_TABLE;

SELECT *
FROM EMPLOYEES
WHERE YEAR(FROM_DAYS(DATEDIFF(CURRENT_DATE,B_DATE))) >
	(SELECT AVG(YEAR(FROM_DAYS(DATEDIFF(CURRENT_DATE,B_DATE)))) FROM EMPLOYEES);

SELECT
EMPL_ID,
YEAR(FROM_DAYS(DATEDIFF(CURRENT_DATE,START_DATE))),
    (SELECT AVG(YEAR(FROM_DAYS(DATEDIFF(CURRENT_DATE,START_DATE))))
    FROM JOB_HISTORY)
FROM JOB_HISTORY;