-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


ALTER TABLE IF EXISTS public.sales_detail DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS public.sales_detail DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS public.product_type DROP CONSTRAINT IF EXISTS None;



DROP TABLE IF EXISTS public.sales_transaction;

CREATE TABLE IF NOT EXISTS public.sales_transaction
(
    transaction_id integer NOT NULL,
    date date NOT NULL,
    "time" time without time zone NOT NULL,
    sales_outlet integer NOT NULL,
    staff integer NOT NULL,
    customer integer,
    PRIMARY KEY (transaction_id)
);

DROP TABLE IF EXISTS public.product;

CREATE TABLE IF NOT EXISTS public.product
(
    product_id integer NOT NULL,
    product character varying(50) NOT NULL,
    description text NOT NULL,
    price numeric NOT NULL,
    PRIMARY KEY (product_id)
);

DROP TABLE IF EXISTS public.sales_detail;

CREATE TABLE IF NOT EXISTS public.sales_detail
(
    sales_detail_id integer NOT NULL,
    transaction_id integer NOT NULL,
    product_id integer NOT NULL,
    quantity integer NOT NULL,
    price integer NOT NULL,
    PRIMARY KEY (sales_detail_id)
);

DROP TABLE IF EXISTS public.product_type;

CREATE TABLE IF NOT EXISTS public.product_type
(
    product_type_id integer NOT NULL,
    product_id integer NOT NULL,
    category character varying NOT NULL,
    type character varying NOT NULL,
    PRIMARY KEY (product_type_id)
);

ALTER TABLE IF EXISTS public.sales_detail
    ADD FOREIGN KEY (transaction_id)
    REFERENCES public.sales_transaction (transaction_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.sales_detail
    ADD FOREIGN KEY (product_id)
    REFERENCES public.product (product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.product_type
    ADD FOREIGN KEY (product_id)
    REFERENCES public.product (product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;